version: "2"
services:
  teamcity-server:
    image: jetbrains/teamcity-server:2018.1.3
    restart: always
    container_name: teamcity-server
    networks:
      teamcity:
        ipv4_address: 172.25.0.2
    ports:
      - "8112:8111"
    volumes:
      - /ext/teamcity/data_dir:/data/teamcity_server/datadir
      - /ext/teamcity/log_dir:/opt/teamcity/logs
  teamcity-dotnet-agent:
    image: scrooge/teamcity-agent:1.0
    restart: always
    container_name: teamcity-dotnet-agent
    networks:
      teamcity:
        ipv4_address: 172.25.0.3
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - AGENT_NAME=dotnet_agent
      - DOCKER_IN_DOCKER=start
    privileged: true
    volumes:
#      - ./buildagent:/opt/buildagent
#      - ./docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
      - /ext/teamcity/agent-data/kubeconfig:/home/primelabsx/.kube
      - /ext/teamcity/agent-data/conf:/data/teamcity_agent/conf
      - /ext/teamcity/agent-data/work:/opt/buildagent/work
      - /ext/teamcity/agent-data/temp:/opt/buildagent/temp
      - /ext/teamcity/agent-data/plugins:/opt/buildagent/plugins
      - /ext/teamcity/agent-data/tools:/opt/buildagent/tools
      - /ext/teamcity/agent-data/system:/opt/buildagent/system
#      - /home/teamcity/docker-compose-poc/TeamCity/agent-data/openvpn:/etc/openvpn/
      - /ext/teamcity/agent-data/${KubernetesRepositoryName}:/${KubernetesRepositoryName}
networks:
  teamcity:
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/24
         gateway: 172.25.0.1
