version: '2'
services:
    nginx-reverse-reload:
      image: lykkex/loadbalancer
      container_name: nginx-reverse-reload
      ports:
         - "80:80"
         - "443:443"
         - "8001:8001"
      volumes:
         - ./certs:/etc/nginx/certs
         - ./sites-enabled:/etc/nginx/sites-enabled
         - ./include-static:/etc/nginx/include-static
         - ./nginx.conf:/etc/nginx/nginx.conf
         - ./logs:/var/log/nginx
